debug: true

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:identity.p12
    key-store-password: identity
    trust-store-type: PKCS12
    trust-store: classpath:http-trust.p12
    trust-store-password: http-trust
    client-auth: need
